name: CI

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
      channel:
        description: 'Channel (release, beta, alpha)'
        required: true
      changelog:
        description: 'Changelog'
        required: false


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Zip Datapack
        run: |
          mkdir -p target
          zip -r target/GUIAdminUtils.zip pack.mcmeta data
      - uses: cloudnode-pro/modrinth-publish@v2
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: QjLHfiSI
          version: ${{ inputs.version }}
          loaders: |-
            datapack
          game-versions: |-
            1.21.6
            1.21.7
            1.21.8
            1.21.9
            1.21.10
            1.21.11
          files: target/GUIAdminUtils.zip
          channel: ${{ inputs.channel }}
          changelog: ${{ inputs.changelog }}
          
